"""
Phase 5D — Triton Codegen

同一个 FlashAttentionKernelIR，输出 Triton kernel
对比：相同算法，Triton 帮你管了什么
"""

from attention_ir import AttentionOp, FlashAttentionKernelIR, lower_to_flash


def codegen_triton(ir: FlashAttentionKernelIR) -> str:
    op = ir.op
    Br = ir.Br
    Bc = ir.Bc
    D  = op.head_dim

    code = f'''\
# AUTO-GENERATED by codegen_triton.py
# FlashAttentionKernelIR: N={op.seq_len} D={D} Br={Br} Bc={Bc}
import torch
import triton
import triton.language as tl

@triton.jit
def flash_attention_triton(
    Q_ptr, K_ptr, V_ptr, O_ptr,
    N: tl.constexpr,
    D: tl.constexpr,
    Br: tl.constexpr,
    Bc: tl.constexpr,
):
    # program_id → query block
    q_block = tl.program_id(0)
    q_start = q_block * Br

    scale = 1.0 / tl.sqrt(float(D))

    # offsets
    q_offs = q_start + tl.arange(0, Br)   # [Br]
    d_offs = tl.arange(0, D)               # [D]
    k_offs = tl.arange(0, Bc)             # [Bc]

    # load Q tile [Br, D]
    Q_mask = q_offs[:, None] < N
    Q = tl.load(
        Q_ptr + q_offs[:, None] * D + d_offs[None, :],
        mask=Q_mask, other=0.0)

    # online softmax state
    m = tl.full([Br], float("-inf"), dtype=tl.float32)
    l = tl.zeros([Br], dtype=tl.float32)
    O = tl.zeros([Br, D], dtype=tl.float32)

    # KV tile loop
    num_kv = tl.cdiv(N, Bc)
    for kv in range(num_kv):
        kv_start = kv * Bc

        # load K tile [Bc, D]
        k_rows = kv_start + k_offs
        K_mask = k_rows[:, None] < N
        K = tl.load(
            K_ptr + k_rows[:, None] * D + d_offs[None, :],
            mask=K_mask, other=0.0)

        # load V tile [Bc, D]
        V = tl.load(
            V_ptr + k_rows[:, None] * D + d_offs[None, :],
            mask=K_mask, other=0.0)

        # S = Q @ K^T * scale  [Br, Bc]
        S = tl.dot(Q, tl.trans(K)) * scale

        # mask out-of-bounds
        S = tl.where(k_rows[None, :] < N, S, float("-inf"))

        # online softmax update
        m_new = tl.maximum(m, tl.max(S, axis=1))

        alpha = tl.exp(m - m_new)
        P = tl.exp(S - m_new[:, None])
        l_local = tl.sum(P, axis=1)

        l = alpha * l + l_local
        O = alpha[:, None] * O + tl.dot(P.to(tl.float32), V)
        m = m_new

    # normalize and store
    O = O / l[:, None]
    out_mask = q_offs[:, None] < N
    tl.store(
        O_ptr + q_offs[:, None] * D + d_offs[None, :],
        O, mask=out_mask)


def run_flash_triton(Q, K, V, Br={Br}, Bc={Bc}):
    N, D = Q.shape
    O = torch.empty_like(Q)
    grid = (triton.cdiv(N, Br),)
    flash_attention_triton[grid](
        Q, K, V, O,
        N=N, D=D, Br=Br, Bc=Bc)
    return O


if __name__ == "__main__":
    import time
    torch.manual_seed(42)
    device = "cuda"

    print("Phase 5D — Triton codegen (Br={Br} Bc={Bc} D={D})")
    print("="*50)

    for N in [128, 512, 1024, 2048]:
        Q = torch.randn(N, {D}, device=device) * 0.1
        K = torch.randn(N, {D}, device=device) * 0.1
        V = torch.randn(N, {D}, device=device) * 0.1

        # reference
        scale = 1.0 / ({D} ** 0.5)
        S_ref = torch.matmul(Q, K.T) * scale
        P_ref = torch.softmax(S_ref, dim=-1)
        O_ref = torch.matmul(P_ref, V)

        # triton
        O_tri = run_flash_triton(Q, K, V, Br={Br}, Bc={Bc})

        max_err = (O_tri - O_ref).abs().max().item()
        bad = ((O_tri - O_ref).abs() /
               (O_ref.abs() + 1e-6) > 1e-3).sum().item()
        status = "PASSED" if bad == 0 else "FAILED"

        # perf
        for _ in range(5): run_flash_triton(Q, K, V)
        torch.cuda.synchronize()
        t = time.perf_counter()
        for _ in range(50): run_flash_triton(Q, K, V)
        torch.cuda.synchronize()
        ms = (time.perf_counter() - t) / 50 * 1000

        print(f"N={{N:5d}}: {{status}}  max_err={{max_err:.6f}}  {{ms:.3f}}ms")

    print()
    print("CUDA codegen reference:")
    print("  N=1024 Br={Br} Bc={Bc}: 0.590ms  (from codegen_cuda.py)")
    print("  N=2048 Br={Br} Bc={Bc}: 1.784ms")
    print()
    print("Difference = what Triton handles for you:")
    print("  - smem allocation (automatic)")
    print("  - warp-level reduction (tl.sum, tl.max)")
    print("  - memory coalescing (tl.load with masks)")
    print("  - tl.dot → Tensor Core dispatch (if FP16)")
'''
    return code


if __name__ == "__main__":
    import os

    op = AttentionOp(seq_len=1024, head_dim=64, dtype="fp32")
    ir = lower_to_flash(op, Br=16, Bc=16, backend="triton")

    src = codegen_triton(ir)
    fname = "gen_triton_Br16_Bc16.py"
    with open(fname, "w") as f:
        f.write(src)

    print(f"Generated: {fname}")
    print("Running...")
    os.system(f"python {fname}")
