"""
Phase 5D — CUDA Codegen

输入：FlashAttentionKernelIR
输出：可编译的 .cu 源文件
"""

from attention_ir import (
    AttentionOp, FlashAttentionKernelIR,
    lower_to_flash, search_tile_sizes
)


def codegen_cuda(ir: FlashAttentionKernelIR) -> str:
    op  = ir.op
    Br  = ir.Br
    Bc  = ir.Bc
    D   = op.head_dim
    N   = op.seq_len

    smem_bytes = ir.smem_layout.total_bytes()
    threads    = ir.thread_mapping.threads_per_block

    # smem offsets
    q_offset = 0
    k_offset = Br * D
    v_offset = k_offset + Bc * D
    s_offset = v_offset + Bc * D

    code = f"""\
// AUTO-GENERATED by codegen_cuda.py
// FlashAttentionKernelIR: N={N} D={D} Br={Br} Bc={Bc}
// smem={smem_bytes//1024}KB  threads={threads}
#include <stdio.h>
#include <math.h>
#include <cuda_runtime.h>

#define Br {Br}
#define Bc {Bc}
#define D  {D}
#define WARP_SIZE 32

__device__ float warp_reduce_sum(float val) {{
    for (int offset = 16; offset > 0; offset >>= 1)
        val += __shfl_down_sync(0xffffffff, val, offset);
    return val;
}}

__device__ float warp_reduce_max(float val) {{
    for (int offset = 16; offset > 0; offset >>= 1)
        val = fmaxf(val, __shfl_down_sync(0xffffffff, val, offset));
    return val;
}}

__global__ void flash_attention_generated(
    const float* __restrict__ Q,
    const float* __restrict__ K,
    const float* __restrict__ V,
    float* __restrict__ O,
    int N)
{{
    int warp_id = threadIdx.x / WARP_SIZE;
    int lane    = threadIdx.x % WARP_SIZE;
    int q_row   = blockIdx.x * Br + warp_id;

    extern __shared__ float smem[];
    float* smem_Q = smem + {q_offset};
    float* smem_K = smem + {k_offset};
    float* smem_V = smem + {v_offset};
    float* smem_S = smem + {s_offset};

    // load Q tile
    if (q_row < N) {{
        for (int d = lane; d < D; d += WARP_SIZE)
            smem_Q[warp_id * D + d] = Q[q_row * D + d];
    }} else {{
        for (int d = lane; d < D; d += WARP_SIZE)
            smem_Q[warp_id * D + d] = 0.0f;
    }}

    float m   = -1e9f;
    float l   = 0.0f;
    float acc[D / WARP_SIZE];
    #pragma unroll
    for (int i = 0; i < D / WARP_SIZE; i++) acc[i] = 0.0f;

    const float scale = 1.0f / sqrtf((float)D);

    __syncthreads();

    const int num_kv = (N + Bc - 1) / Bc;
    const int total_threads = blockDim.x;

    for (int kv = 0; kv < num_kv; kv++) {{
        int kv_start = kv * Bc;

        // load K, V tiles
        for (int i = threadIdx.x; i < Bc * D; i += total_threads) {{
            int r = i / D, c = i % D;
            int kr = kv_start + r;
            smem_K[r * D + c] = (kr < N) ? K[kr * D + c] : 0.0f;
            smem_V[r * D + c] = (kr < N) ? V[kr * D + c] : 0.0f;
        }}
        __syncthreads();

        // S[warp_id, j] = Q[warp_id] · K[j] * scale
        for (int j = 0; j < Bc; j++) {{
            float partial = 0.0f;
            for (int d = lane; d < D; d += WARP_SIZE)
                partial += smem_Q[warp_id * D + d] * smem_K[j * D + d];
            partial = warp_reduce_sum(partial);
            if (lane == 0)
                smem_S[warp_id * Bc + j] = partial * scale;
        }}

        // online softmax
        float m_new = -1e9f;
        for (int j = lane; j < Bc; j += WARP_SIZE)
            m_new = fmaxf(m_new, smem_S[warp_id * Bc + j]);
        m_new = warp_reduce_max(m_new);
        m_new = __shfl_sync(0xffffffff, m_new, 0);

        float P[Bc];
        float l_local_partial = 0.0f;
        #pragma unroll
        for (int j = 0; j < Bc; j++)
            P[j] = expf(smem_S[warp_id * Bc + j] - m_new);
        for (int j = lane; j < Bc; j += WARP_SIZE)
            l_local_partial += P[j];
        float l_local = warp_reduce_sum(l_local_partial);
        l_local = __shfl_sync(0xffffffff, l_local, 0);

        float alpha = expf(m - m_new);
        l = alpha * l + l_local;

        #pragma unroll
        for (int di = 0; di < D / WARP_SIZE; di++) {{
            int d = lane + di * WARP_SIZE;
            float pv = 0.0f;
            #pragma unroll
            for (int j = 0; j < Bc; j++)
                pv += P[j] * smem_V[j * D + d];
            acc[di] = alpha * acc[di] + pv;
        }}
        m = m_new;
        __syncthreads();
    }}

    if (q_row < N) {{
        #pragma unroll
        for (int di = 0; di < D / WARP_SIZE; di++)
            O[q_row * D + di * WARP_SIZE + lane] = acc[di] / l;
    }}
}}

// CPU reference
void attention_cpu(const float* Q, const float* K, const float* V,
                   float* O, int N, int Dh) {{
    float scale = 1.0f / sqrtf((float)Dh);
    float* S = new float[N * N];
    for (int i = 0; i < N; i++)
        for (int j = 0; j < N; j++) {{
            float dot = 0;
            for (int d = 0; d < Dh; d++) dot += Q[i*Dh+d] * K[j*Dh+d];
            S[i*N+j] = dot * scale;
        }}
    for (int i = 0; i < N; i++) {{
        float mv = S[i*N];
        for (int j = 1; j < N; j++) mv = fmaxf(mv, S[i*N+j]);
        float s = 0;
        for (int j = 0; j < N; j++) {{ S[i*N+j] = expf(S[i*N+j]-mv); s += S[i*N+j]; }}
        for (int j = 0; j < N; j++) S[i*N+j] /= s;
    }}
    for (int i = 0; i < N; i++)
        for (int d = 0; d < Dh; d++) {{
            float acc = 0;
            for (int j = 0; j < N; j++) acc += S[i*N+j] * V[j*Dh+d];
            O[i*Dh+d] = acc;
        }}
    delete[] S;
}}

int main() {{
    const int N = {N}, Dh = {D};

    float *hQ = new float[N*Dh], *hK = new float[N*Dh];
    float *hV = new float[N*Dh], *hO = new float[N*Dh];
    float *hO_ref = new float[N*Dh];

    srand(42);
    for (int i = 0; i < N*Dh; i++) {{
        hQ[i] = ((float)rand()/RAND_MAX - 0.5f) * 0.1f;
        hK[i] = ((float)rand()/RAND_MAX - 0.5f) * 0.1f;
        hV[i] = ((float)rand()/RAND_MAX - 0.5f) * 0.1f;
    }}
    attention_cpu(hQ, hK, hV, hO_ref, N, Dh);

    float *dQ, *dK, *dV, *dO;
    cudaMalloc(&dQ, N*Dh*sizeof(float));
    cudaMalloc(&dK, N*Dh*sizeof(float));
    cudaMalloc(&dV, N*Dh*sizeof(float));
    cudaMalloc(&dO, N*Dh*sizeof(float));
    cudaMemcpy(dQ, hQ, N*Dh*sizeof(float), cudaMemcpyHostToDevice);
    cudaMemcpy(dK, hK, N*Dh*sizeof(float), cudaMemcpyHostToDevice);
    cudaMemcpy(dV, hV, N*Dh*sizeof(float), cudaMemcpyHostToDevice);

    dim3 block({threads});
    dim3 grid((N + Br - 1) / Br);

    flash_attention_generated<<<grid, block, {smem_bytes}>>>(dQ, dK, dV, dO, N);
    cudaDeviceSynchronize();

    cudaError_t err = cudaGetLastError();
    if (err != cudaSuccess) {{
        printf("CUDA error: %s\\n", cudaGetErrorString(err));
        return 1;
    }}

    cudaMemcpy(hO, dO, N*Dh*sizeof(float), cudaMemcpyDeviceToHost);

    // verify
    float max_err = 0; int bad = 0;
    for (int i = 0; i < N*Dh; i++) {{
        float diff = fabsf(hO_ref[i] - hO[i]);
        float rel  = diff / (fabsf(hO_ref[i]) + 1e-6f);
        if (rel > max_err) max_err = rel;
        if (rel > 1e-3f) bad++;
    }}
    printf("Correctness: %s (max_rel_err=%.6f bad=%d/%d)\\n",
           bad==0?"PASSED":"FAILED", max_err, bad, N*Dh);

    // perf
    cudaEvent_t start, stop;
    cudaEventCreate(&start); cudaEventCreate(&stop);
    cudaEventRecord(start);
    for (int i = 0; i < 10; i++)
        flash_attention_generated<<<grid, block, {smem_bytes}>>>(dQ, dK, dV, dO, N);
    cudaEventRecord(stop);
    cudaEventSynchronize(stop);
    float ms; cudaEventElapsedTime(&ms, start, stop); ms /= 10;
    printf("N=%d D=%d Br=%d Bc=%d: %.3f ms\\n", N, Dh, Br, Bc, ms);

    cudaFree(dQ); cudaFree(dK); cudaFree(dV); cudaFree(dO);
    delete[] hQ; delete[] hK; delete[] hV; delete[] hO; delete[] hO_ref;
    return 0;
}}
"""
    return code


if __name__ == "__main__":
    import subprocess, os

    print("Phase 5D — CUDA Codegen")
    print("="*50)

    # 对不同 N 和 tile size 生成并编译
    configs = [
        (1024, 64, 16, 16),
        (1024, 64, 32, 32),
        (2048, 64, 16, 16),
        (2048, 64, 32, 32),
    ]

    results = []
    for N, D, Br, Bc in configs:
        op = AttentionOp(seq_len=N, head_dim=D, dtype="fp32")
        ir = lower_to_flash(op, Br=Br, Bc=Bc, backend="cuda")

        errors = ir.validate()
        if errors:
            print(f"N={N} Br={Br} Bc={Bc}: SKIP ({errors})")
            continue

        # codegen
        src = codegen_cuda(ir)
        fname = f"gen_N{N}_Br{Br}_Bc{Bc}.cu"
        with open(fname, "w") as f:
            f.write(src)

        # compile
        binary = fname.replace(".cu", "")
        ret = subprocess.run(
            ["nvcc", "-O3", "-arch=sm_89", fname, "-o", binary],
            capture_output=True, text=True)

        if ret.returncode != 0:
            print(f"COMPILE ERROR: {ret.stderr[:200]}")
            continue

        # run
        ret = subprocess.run([f"./{binary}"],
                             capture_output=True, text=True, timeout=30)
        output = ret.stdout.strip()
        print(f"\nN={N} Br={Br} Bc={Bc}:")
        for line in output.split('\n'):
            print(f"  {line}")
        results.append((N, Br, Bc, output))

    print("\n" + "="*50)
    print("Generated files:")
    for f in os.listdir('.'):
        if f.startswith('gen_') and f.endswith('.cu'):
            print(f"  {f}")
